In [ ]:
import pandas as pd
import numpy as np
import re 

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
df=pd.read_csv("/content/products_description.csv")

In [ ]:
df.head()

Unnamed: 0 product_type                                        description
0           0    lip_liner  Lippie Pencil A long-wearing and high-intensit...
1           1     lipstick  Blotted Lip Sheer matte lipstick that creates ...
2           2     lipstick  Lippie Stix Formula contains Vitamin E, Mango,...
3           3   foundation  Developed for the Selfie Age, our buildable fu...
4           4     lipstick  All of our products are free from lead and hea...

In [ ]:
df.columns

Index(['Unnamed: 0', 'product_type', 'description'], dtype='object')

In [ ]:
df.shape

(906, 3)

In [ ]:
df['product_type'].value_counts()

foundation     159
lipstick       148
eyeliner       145
mascara         91
eyeshadow       86
blush           75
bronzer         69
nail_polish     60
eyebrow         45
lip_liner       28
Name: product_type, dtype: int64

# **`Preprocessing`**




In [ ]:
X=df['description']
y=df['product_type']

In [ ]:
X[902]

'Physicians Formula Organic Wear FakeOut Mascara is the 1st EVER mascara with 100% natural origin lash extension fibers for the full-on fringe of false lashes without irritation.The innovative formula amplifies lash volume, length & curl. Plus the oversized brush creates a fabulously false lash effect instantly!Features:  100% of the Total Ingredients are from Natural Origin  70% of the Total Ingredients are from Organic FarmingDirections: Sweep mascara brush from lash base to tips. Apply multiple coats for added volume.Ingredients: Citrus Aurantium Dulcis (Orange) Fruit Water*, Glycerin*, Glyceryl \r\r\nStearate SE, Beeswax*, Microcrystalline Cellulose, Copernicia Cerifera \r\r\n(Carnauba) Wax*, Tapioca Starch*, Hydrolyzed Corn Starch, Stearic Acid, \r\r\nJojoba Esters, Oryza Sativa (Rice) Powder*, Oryza Sativa (Rice) \r\r\nExtract*, Ceiba Pentandra Fiber Powder, Cellulose, Nylon-10/10, Aloe \r\r\nBarbadensis Leaf Extract*, Cucumis Sativus (Cucumber) Fruit Extract*, \r\r\nGlycine Soja

In [ ]:
def preprocess(text):
  text=re.sub(r'<.*?>'," ",text)#html
  text=re.sub(r'https\S+'," ",text)
  text=re.sub(r'Link'," ",text)
  text=re.sub(r'[^A-Za-z]'," ",text) 
  return text

In [ ]:
preprocess(X[902])

'Physicians Formula Organic Wear FakeOut Mascara is the  st EVER mascara with      natural origin lash extension fibers for the full on fringe of false lashes without irritation The innovative formula amplifies lash volume  length   curl  Plus the oversized brush creates a fabulously false lash effect instantly Features        of the Total Ingredients are from Natural Origin      of the Total Ingredients are from Organic FarmingDirections  Sweep mascara brush from lash base to tips  Apply multiple coats for added volume Ingredients  Citrus Aurantium Dulcis  Orange  Fruit Water   Glycerin   Glyceryl    Stearate SE  Beeswax   Microcrystalline Cellulose  Copernicia Cerifera     Carnauba  Wax   Tapioca Starch   Hydrolyzed Corn Starch  Stearic Acid     Jojoba Esters  Oryza Sativa  Rice  Powder   Oryza Sativa  Rice     Extract   Ceiba Pentandra Fiber Powder  Cellulose  Nylon        Aloe    Barbadensis Leaf Extract   Cucumis Sativus  Cucumber  Fruit Extract      Glycine Soja  Soybean  Oil   O

In [ ]:
X=X.apply(preprocess)

In [ ]:
X

0      Lippie Pencil A long wearing and high intensit...
1      Blotted Lip Sheer matte lipstick that creates ...
2      Lippie Stix Formula contains Vitamin E  Mango ...
3      Developed for the Selfie Age  our buildable fu...
4      All of our products are free from lead and hea...
                             ...                        
901    You will fall in love with Pacifica s long las...
902    Physicians Formula Organic Wear FakeOut Mascar...
903    Physicians Formula Organic Wear Lash Boosting ...
904    Voluminous   Volume Building Waterproof Mascar...
905    Finally  a natural mascara you can feel good a...
Name: description, Length: 906, dtype: object

In [ ]:
def nlp_preprocess(text):
  text=text.lower()
  text=text.split()
  lemma=WordNetLemmatizer()
  text=[lemma.lemmatize(word) for word in text if word not in set(stopwords.words('english'))]
  text=' '.join(text)
  
  return text

In [ ]:
nlp_preprocess(X[902])

'physician formula organic wear fakeout mascara st ever mascara natural origin lash extension fiber full fringe false lash without irritation innovative formula amplifies lash volume length curl plus oversized brush creates fabulously false lash effect instantly feature total ingredient natural origin total ingredient organic farmingdirections sweep mascara brush lash base tip apply multiple coat added volume ingredient citrus aurantium dulcis orange fruit water glycerin glyceryl stearate se beeswax microcrystalline cellulose copernicia cerifera carnauba wax tapioca starch hydrolyzed corn starch stearic acid jojoba ester oryza sativa rice powder oryza sativa rice extract ceiba pentandra fiber powder cellulose nylon aloe barbadensis leaf extract cucumis sativus cucumber fruit extract glycine soja soybean oil olea europaea olive leaf extract glycerin magnesium aluminum silicate water glyceryl caprylate leuconostoc radish root ferment filtrate may contain iron oxide titanium dioxide ingre

In [ ]:
X=X.apply(nlp_preprocess)

In [ ]:
X[902]

'physician formula organic wear fakeout mascara st ever mascara natural origin lash extension fiber full fringe false lash without irritation innovative formula amplifies lash volume length curl plus oversized brush creates fabulously false lash effect instantly feature total ingredient natural origin total ingredient organic farmingdirections sweep mascara brush lash base tip apply multiple coat added volume ingredient citrus aurantium dulcis orange fruit water glycerin glyceryl stearate se beeswax microcrystalline cellulose copernicia cerifera carnauba wax tapioca starch hydrolyzed corn starch stearic acid jojoba ester oryza sativa rice powder oryza sativa rice extract ceiba pentandra fiber powder cellulose nylon aloe barbadensis leaf extract cucumis sativus cucumber fruit extract glycine soja soybean oil olea europaea olive leaf extract glycerin magnesium aluminum silicate water glyceryl caprylate leuconostoc radish root ferment filtrate may contain iron oxide titanium dioxide ingre

In [ ]:
from sklearn.preprocessing import LabelEncoder
encorder=LabelEncoder()
y=encorder.fit_transform(y)
y

array([6, 7, 7, 5, 7, 5, 5, 3, 4, 5, 4, 7, 4, 0, 4, 5, 1, 1, 7, 7, 5, 4,
       0, 8, 4, 7, 7, 3, 3, 8, 0, 4, 4, 4, 4, 4, 8, 7, 7, 8, 6, 3, 4, 5,
       0, 5, 5, 5, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 5, 5, 3, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7,
       7, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 3, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 5, 5,
       1, 1, 1, 1, 1, 5, 0, 0, 0, 0, 0, 0, 7, 6, 6, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 2, 2,
       2, 2, 2, 3, 3, 3, 3, 3, 3, 8, 8, 8, 8, 8, 8,

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=0)

In [ ]:
x_train.shape,y_train.shape

((724,), (724,))

# **`Converting string to numbers`**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import metrics

In [ ]:
bog=CountVectorizer()

In [ ]:
x_bog=bog.fit_transform(x_train).toarray()

In [ ]:
x_bog.shape

(724, 4566)

In [ ]:
x_bog_test=bog.transform(x_test).toarray()

In [ ]:
x_bog_test.shape

(182, 4566)

# **`TFidf`**

In [ ]:
tfidf=TfidfVectorizer(max_features=1000)
x_tfidf=tfidf.fit_transform(x_train).toarray()

In [ ]:
x_tfidf

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.11504023, 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.07748246, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
x_tfidf_test=tfidf.transform(x_test).toarray()

# **`Model`**

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
regressor=LogisticRegression()

In [ ]:
regressor.fit(x_bog,y_train)

LogisticRegression()

In [ ]:
y_pred=regressor.predict(x_bog_test)

In [ ]:
regressor.score(x_bog_test,y_test)

0.8571428571428571

In [ ]:
score=metrics.accuracy_score(y_test,y_pred)
score

0.8571428571428571

In [ ]:
#tfidf

In [ ]:
reg=LogisticRegression()
reg.fit(x_tfidf,y_train)

LogisticRegression()

In [ ]:
y_pred=reg.predict(x_tfidf_test)

In [ ]:
reg.score(x_tfidf_test,y_test)

0.8241758241758241

svm

In [ ]:
from sklearn.svm import SVC 

In [ ]:
Svm=SVC()
Svm.fit(x_tfidf,y_train)

SVC()

In [ ]:
Svm.score(x_tfidf_test,y_test)

0.8351648351648352

In [ ]:
s=SVC()
s.fit(x_bog,y_train)

SVC()

In [ ]:
s.score(x_bog_test,y_test)

0.6648351648351648

# **`Embedding`**

In [ ]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder=OneHotEncoder()
y1=onehot_encoder.fit_transform(df['product_type'].values.reshape(-1,1)).toarray()
y1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [ ]:
X

0      lippie pencil long wearing high intensity lip ...
1      blotted lip sheer matte lipstick creates perfe...
2      lippie stix formula contains vitamin e mango a...
3      developed selfie age buildable full coverage n...
4      product free lead heavy metal parabens phthala...
                             ...                        
901    fall love pacifica long lasting nourishing nat...
902    physician formula organic wear fakeout mascara...
903    physician formula organic wear lash boosting m...
904    voluminous volume building waterproof mascara ...
905    finally natural mascara feel good putting lash...
Name: description, Length: 906, dtype: object

In [ ]:
x_cnn_train,x_cnn_test,y_cnn_train,y_cnn_test=train_test_split(X,y1,test_size=0.2,random_state=2)

In [ ]:
from keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer=Tokenizer(num_words=5000)
tokenizer.fit_on_texts(x_cnn_train)

In [ ]:
len(tokenizer.word_index)+1

4588

In [ ]:
x_train_emb=tokenizer.texts_to_sequences(x_cnn_train)
x_test_emb=tokenizer.texts_to_sequences(x_cnn_test)

In [ ]:
print(x_train[12])
print(x_train_emb[12])

multi purpose pressed powder may used blush eye shadow blended antioxidant certified organic fruit berry amp botanical made without gluten containing ingredient mica free pink parfait papaya offer natural ultra sheer semi matte finish petal beautiful crushed red rose found pink parfait valued natural color delightful aroma provide acai berry offer natural ultra sheer satin finish mica added vegan image one pink parfait image two papaya image three acai berry model image four wearing papaya model image five wearing acai berry see demonstration papaya click video fast forward enjoy product ewg verified x rated clean think dirty app bpa phthalate free packaging plastic part compact recyclable tiny fleck fruit botanical particle may visible powder pink parfait papaya titanium dioxide mica free net weight gm
[114, 411, 1788, 39, 220, 1088, 118, 485, 18, 96, 149, 11, 1204, 784, 120, 1531, 2115, 18, 785, 96, 55, 53, 1205, 4, 39, 31, 120, 18, 39, 26, 29, 441, 4, 39, 203, 786, 11, 837, 71, 38, 

In [ ]:
from keras.preprocessing.sequence import pad_sequences

In [ ]:
maxlen=600
x_train_pad=pad_sequences(x_train_emb,padding='post',maxlen=maxlen)
x_test_pad=pad_sequences(x_test_emb,padding='post',maxlen=maxlen)

In [ ]:
import tensorflow as tf
import keras 

In [ ]:
from keras.models import Sequential

In [ ]:
vocab_size=len(tokenizer.word_index)+1
input_dim=100
lens=maxlen

model=Sequential()
model.add(tf.keras.layers.Embedding(vocab_size,input_dim,input_length=lens))
model.add(tf.keras.layers.Conv1D(128,3,activation='relu'))
model.add(tf.keras.layers.GlobalMaxPooling1D())
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 600, 100)          458800    
                                                                 
 conv1d (Conv1D)             (None, 598, 128)          38528     
                                                                 
 global_max_pooling1d (Globa  (None, 128)              0         
 lMaxPooling1D)                                                  
                                                                 
 flatten (Flatten)           (None, 128)               0         
                                                                 
 dense (Dense)               (None, 128)               16512     
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                      

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(x_train_pad,y_cnn_train,epochs=5,verbose=2,validation_data=(x_test_pad,y_cnn_test))

Epoch 1/5
23/23 - 4s - loss: 2.2316 - accuracy: 0.1989 - val_loss: 2.1424 - val_accuracy: 0.3022 - 4s/epoch - 153ms/step
Epoch 2/5
23/23 - 3s - loss: 2.0490 - accuracy: 0.4157 - val_loss: 1.9377 - val_accuracy: 0.5055 - 3s/epoch - 111ms/step
Epoch 3/5
23/23 - 3s - loss: 1.6588 - accuracy: 0.5801 - val_loss: 1.4038 - val_accuracy: 0.5934 - 3s/epoch - 110ms/step
Epoch 4/5
23/23 - 3s - loss: 0.9917 - accuracy: 0.7762 - val_loss: 0.8735 - val_accuracy: 0.7418 - 3s/epoch - 111ms/step
Epoch 5/5
23/23 - 3s - loss: 0.5201 - accuracy: 0.8923 - val_loss: 0.6199 - val_accuracy: 0.8132 - 3s/epoch - 110ms/step


In [ ]:
model.evaluate(x_test_pad,y_cnn_test)

6/6 [==============================] - 0s 29ms/step - loss: 0.6199 - accuracy: 0.8132


[0.6199009418487549, 0.8131868243217468]

# BBC

In [ ]:
import pandas as pd
import numpy as np
import re 

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [ ]:
!unzip "/content/bbc-text.csv.zip" -d "/content/"

Archive:  /content/bbc-text.csv.zip
  inflating: /content/bbc-text.csv   


In [ ]:
data = pd.read_csv("/content/bbc-text.csv")
data.head()

category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [ ]:
def preprocess(text):
  text=re.sub(r'<.*?>'," ",text)#html
  text=re.sub(r'https\S+'," ",text)
  text=re.sub(r'Link'," ",text)
  text=re.sub(r'[^A-Za-z]'," ",text) 
  return text


def nlp_preprocess(text):
  text=text.lower()
  text=text.split()
  lemma=WordNetLemmatizer()
  text=[lemma.lemmatize(word) for word in text if word not in set(stopwords.words('english'))]
  text=' '.join(text)
  
  return text

  
data.text = data.text.apply(preprocess)
data.text = data.text.apply(nlp_preprocess)

In [ ]:
X = data.text
y = data.category
from sklearn.preprocessing import LabelEncoder
encorder=LabelEncoder()
y=encorder.fit_transform(y)
y

array([4, 0, 3, ..., 1, 2, 3])

# **`Converting string to numbers`**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import metrics

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=0)

In [ ]:
bog=CountVectorizer()

In [ ]:
x_bog=bog.fit_transform(x_train).toarray()

In [ ]:
x_bog.shape

(1780, 22686)

In [ ]:
x_bog_test=bog.transform(x_test).toarray()

In [ ]:
x_bog_test.shape

(445, 22686)

# **`TFidf`**

In [ ]:
tfidf=TfidfVectorizer(max_features=1000)
x_tfidf=tfidf.fit_transform(x_train).toarray()

In [ ]:
x_tfidf

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.034394  , 0.02594329, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
x_tfidf_test=tfidf.transform(x_test).toarray()

# **`Model`**

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
regressor=LogisticRegression()

In [ ]:
regressor.fit(x_bog,y_train)

LogisticRegression()

In [ ]:
y_pred=regressor.predict(x_bog_test)

In [ ]:
regressor.score(x_bog_test,y_test)

0.9842696629213483

In [ ]:
score=metrics.accuracy_score(y_test,y_pred)
score

0.9842696629213483

In [ ]:
#tfidf

In [ ]:
reg=LogisticRegression()
reg.fit(x_tfidf,y_train)

LogisticRegression()

In [ ]:
y_pred=reg.predict(x_tfidf_test)

In [ ]:
reg.score(x_tfidf_test,y_test)

0.9842696629213483

svm

In [ ]:
from sklearn.svm import SVC 

In [ ]:
Svm=SVC()
Svm.fit(x_tfidf,y_train)

SVC()

In [ ]:
Svm.score(x_tfidf_test,y_test)

0.9842696629213483

In [ ]:
s=SVC()
s.fit(x_bog,y_train)

SVC()

In [ ]:
s.score(x_bog_test,y_test)

0.9752808988764045

# **`Embedding`**

In [ ]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder=OneHotEncoder()
y1=onehot_encoder.fit_transform(data.category.values.reshape(-1,1)).toarray()
y1

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
x_cnn_train,x_cnn_test,y_cnn_train,y_cnn_test=train_test_split(X,y1,test_size=0.2,random_state=2)

In [ ]:
from keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer=Tokenizer(num_words=5000)
tokenizer.fit_on_texts(x_cnn_train)

In [ ]:
len(tokenizer.word_index)+1

22688

In [ ]:
x_train_emb=tokenizer.texts_to_sequences(x_cnn_train)
x_test_emb=tokenizer.texts_to_sequences(x_cnn_test)

In [ ]:
print(x_train[12])
print(x_train_emb[12])

crude oil price back cold weather across part united state much europe pushed u crude oil price barrel first time almost three month freezing temperature heavy snowfall increased demand heating fuel u stock low fresh fall value dollar helped carry price mark first time since november barrel u crude oil closed new york tuesday opec member said tuesday saw reason cut output although last year peak barrel reached october price well average brent crude also rose london trading adding close much western europe north east america shivering unseasonably low temperature recent day decline u dollar five week low euro also served inflate price dollar moved sharply overnight oil following said chris furness senior market strategist cast dollar continues weaken oil obviously higher several opec member said cut production unlikely citing rising price strong demand oil asia agree need cut supply price much fathi bin shatwan libya oil minister told reuters think need cut unless price falling barrel a

In [ ]:
from keras.preprocessing.sequence import pad_sequences

In [ ]:
maxlen=600
x_train_pad=pad_sequences(x_train_emb,padding='post',maxlen=maxlen)
x_test_pad=pad_sequences(x_test_emb,padding='post',maxlen=maxlen)

In [ ]:
import tensorflow as tf
import keras 

In [ ]:
from keras.models import Sequential

In [ ]:
vocab_size=len(tokenizer.word_index)+1
input_dim=100
lens=maxlen

model=Sequential()
model.add(tf.keras.layers.Embedding(vocab_size,input_dim,input_length=lens))
model.add(tf.keras.layers.Conv1D(128,3,activation='relu'))
model.add(tf.keras.layers.GlobalMaxPooling1D())
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.Dense(5,activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 600, 100)          2268800   
                                                                 
 conv1d_1 (Conv1D)           (None, 598, 128)          38528     
                                                                 
 global_max_pooling1d_1 (Glo  (None, 128)              0         
 balMaxPooling1D)                                                
                                                                 
 flatten_1 (Flatten)         (None, 128)               0         
                                                                 
 dense_2 (Dense)             (None, 128)               16512     
                                                                 
 dense_3 (Dense)             (None, 5)                 645       
                                                      

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(x_train_pad,y_cnn_train,epochs=5,verbose=2,validation_data=(x_test_pad,y_cnn_test))

Epoch 1/5
56/56 - 8s - loss: 1.4817 - accuracy: 0.4567 - val_loss: 1.1302 - val_accuracy: 0.7708 - 8s/epoch - 146ms/step
Epoch 2/5
56/56 - 11s - loss: 0.4590 - accuracy: 0.9298 - val_loss: 0.1824 - val_accuracy: 0.9506 - 11s/epoch - 191ms/step
Epoch 3/5
56/56 - 10s - loss: 0.0695 - accuracy: 0.9854 - val_loss: 0.1285 - val_accuracy: 0.9573 - 10s/epoch - 174ms/step
Epoch 4/5
56/56 - 8s - loss: 0.0162 - accuracy: 0.9989 - val_loss: 0.1080 - val_accuracy: 0.9618 - 8s/epoch - 144ms/step
Epoch 5/5
56/56 - 7s - loss: 0.0063 - accuracy: 1.0000 - val_loss: 0.1060 - val_accuracy: 0.9640 - 7s/epoch - 129ms/step


In [ ]:
model.evaluate(x_test_pad,y_cnn_test)

14/14 [==============================] - 0s 30ms/step - loss: 0.1060 - accuracy: 0.9640


[0.10603150725364685, 0.9640449285507202]